version: '3.1'

services:

  db-dev:
    image: postgres 
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pot-dev
    ports:
      - "5432:5432"
