name: Pot DAPP deployment

on:
  push:
    branches:
      - "main"
  pull_request:
    types: [opened, synchronize]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push image to Heroku registry
        working-directory: ./pot
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "pot-dapp"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
